# Fan control for DBRGN's backplane
ARG GW_MACHINE_NAME

FROM balenalib/${GW_MACHINE_NAME:-%%RESIN_MACHINE_NAME%%}-debian:stretch

RUN apt-get update && \
    apt-get install git python-pip python-rpi.gpio && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/ttn-fan

RUN git clone https://github.com/AmedeeBulle/ttn-fan.git

RUN pip install -r ./ttn-fan/requirements.txt

COPY run.sh ./

CMD ["/opt/ttn-fan/run.sh"]
